### ISSUE TITLE
Ley Martin para walter

### ISSUE THREAD

**Issue by lfalconhao** [JWLsoft/CoquitoCash#3]

**Comment by Jairmf** [comment]
tu no sabes escribir ni un `<td colspan="3">`

**Comment by wgamarra** [comment]
tu no sabes escribir ni un <td colspan="3"> x2

**Comment by Jairmf** [comment]
`hola walter`

**Comment by Jairmf** [comment]
> hello
## putos tdos

**Comment by Jairmf** [comment]
> `<html>
> </html>`

**Comment by wgamarra** [comment]
`shus comentarios`
